2023-10-19 18:40:27.698 UTC [1] LOG:  starting PostgreSQL 16.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-10-19 18:40:27.699 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-10-19 18:40:27.699 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-10-19 18:40:27.726 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-10-19 18:40:27.997 UTC [26] LOG:  database system was interrupted; last known up at 2023-10-12 22:59:26 UTC
2023-10-19 18:40:38.023 UTC [26] LOG:  syncing data directory (pre-fsync), elapsed time: 10.00 s, current path: ./base/16384/3455
2023-10-19 18:40:48.024 UTC [26] LOG:  syncing data directory (pre-fsync), elapsed time: 20.00 s, current path: ./base/16598/2658
2023-10-19 18:40:58.037 UTC [26] LOG:  syncing data directory (pre-fsync), elapsed time: 30.01 s, current path: ./base/5/2674
2023-10-19 18:41:12.277 UTC [26] LOG:  syncing data directory (fsync), elapsed time: 10.00 s, current path: ./base/4/2608
2023-10-19 18:41:17.648 UTC [26] LOG:  database system was not properly shut down; automatic recovery in progress
2023-10-19 18:41:17.894 UTC [26] LOG:  redo starts at 0/642BE18
2023-10-19 18:41:17.899 UTC [26] LOG:  invalid record length at 0/642BF00: expected at least 24, got 0
2023-10-19 18:41:17.899 UTC [26] LOG:  redo done at 0/642BEC8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2023-10-19 18:41:18.149 UTC [24] LOG:  checkpoint starting: end-of-recovery immediate wait
2023-10-19 18:41:18.444 UTC [24] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.122 s, sync=0.028 s, total=0.308 s; sync files=2, longest=0.016 s, average=0.014 s; distance=0 kB, estimate=0 kB; lsn=0/642BF00, redo lsn=0/642BF00
2023-10-19 18:41:18.482 UTC [1] LOG:  database system is ready to accept connections
2023-10-19 18:45:53.465 UTC [40] ERROR:  syntax error at or near "int" at character 57
2023-10-19 18:45:53.465 UTC [40] STATEMENT:  create or replace function exponente(n int) returns rdo int as $$ return n*n $$ language plpython;
2023-10-19 18:46:01.280 UTC [40] ERROR:  syntax error at or near "integer" at character 57
2023-10-19 18:46:01.280 UTC [40] STATEMENT:  create or replace function exponente(n int) returns rdo integer as $$ return n*n $$ language plpython;
2023-10-19 18:46:11.630 UTC [40] ERROR:  language "plpython" does not exist
2023-10-19 18:46:11.630 UTC [40] STATEMENT:  create or replace function exponente(n int) returns integer as $$ return n*n $$ language plpython;
2023-10-19 18:46:36.252 UTC [40] ERROR:  language "plpython3u" does not exist
2023-10-19 18:46:36.252 UTC [40] HINT:  Use CREATE EXTENSION to load the language into the database.
2023-10-19 18:46:36.252 UTC [40] STATEMENT:  create or replace function exponente(n int) returns integer as $$ return n*n $$ language plpython3u;
2023-10-19 18:46:48.002 UTC [40] ERROR:  language "plpython3" does not exist
2023-10-19 18:46:48.002 UTC [40] STATEMENT:  create or replace function exponente(n int) returns integer as $$ return n*n $$ language plpython3;
2023-10-19 18:49:50.632 UTC [40] ERROR:  syntax error at or near "python" at character 1
2023-10-19 18:49:50.632 UTC [40] STATEMENT:  python
	python --version
	;
2023-10-19 18:52:32.033 UTC [40] ERROR:  language "plpython" does not exist
2023-10-19 18:52:32.033 UTC [40] STATEMENT:  create or replace function exponente(n int) returns integer as $$ return n*n $$ language 'plpython';
2023-10-19 18:54:19.609 UTC [40] ERROR:  language "plpy" does not exist
2023-10-19 18:54:19.609 UTC [40] STATEMENT:  create or replace function exponente(n int) returns integer as $$ return n*n $$ language plpy;
2023-10-19 18:54:25.943 UTC [40] ERROR:  language "plpython" does not exist
2023-10-19 18:54:25.943 UTC [40] STATEMENT:  create or replace function exponente(n int) returns integer as $$ return n*n $$ language plpython;
2023-10-19 18:54:39.680 UTC [40] ERROR:  language "plpython" does not exist
2023-10-19 18:54:39.680 UTC [40] STATEMENT:  create or replace function exponente(n int) returns integer as $$ return n*n $$ language PLPYTHON;
2023-10-19 18:54:45.190 UTC [40] ERROR:  language "plpython3u" does not exist
2023-10-19 18:54:45.190 UTC [40] HINT:  Use CREATE EXTENSION to load the language into the database.
2023-10-19 18:54:45.190 UTC [40] STATEMENT:  create or replace function exponente(n int) returns integer as $$ return n*n $$ language PLPYTHON3U;
2023-10-19 18:55:12.516 UTC [40] ERROR:  extension "plpython" is not available
2023-10-19 18:55:12.516 UTC [40] DETAIL:  Could not open extension control file "/usr/local/share/postgresql/extension/plpython.control": No such file or directory.
2023-10-19 18:55:12.516 UTC [40] HINT:  The extension must first be installed on the system where PostgreSQL is running.
2023-10-19 18:55:12.516 UTC [40] STATEMENT:  create extension plpython
	;
2023-10-19 18:56:18.596 UTC [24] LOG:  checkpoint starting: time
2023-10-19 18:56:21.580 UTC [24] LOG:  checkpoint complete: wrote 27 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.754 s, sync=0.064 s, total=2.985 s; sync files=22, longest=0.011 s, average=0.003 s; distance=89 kB, estimate=89 kB; lsn=0/6442698, redo lsn=0/6442660
